import Link from "next/link";

const sections = [
  { id:"overview", title:"01 / WHAT IS ISS", heading:"A laboratory in low Earth orbit.", text:["The International Space Station (ISS) is a permanently crewed modular space station in low Earth orbit. It functions as a research laboratory and a long-duration human-spaceflight platform.","The station has been continuously inhabited since 2 November 2000. Its modules, laboratories, living areas, external trusses, solar arrays, radiators, robotic systems and docking ports operate together as one integrated spacecraft."] },
  { id:"purpose", title:"02 / PURPOSE", heading:"Why keep a laboratory in orbit?", text:["The ISS provides a controlled microgravity environment for research that cannot be reproduced for long periods on Earth. Work aboard the station covers biology, human physiology, physics, materials, combustion, Earth observation and technologies for future exploration.","It also serves as a technology testbed and an educational platform, allowing researchers to study how organisms, fluids, materials and physical processes behave when gravity is no longer the dominant force shaping them."] },
  { id:"stats", title:"03 / STATS", heading:"The numbers behind the station.", text:["The ISS travels in Low Earth Orbit at an inclination of about 51.6 degrees. It moves at roughly 28,000 kilometres per hour and completes about 15.5 orbits of Earth each day, with one orbit taking about 93 minutes.","Its orbit is maintained within roughly 370–460 km mean altitude depending on operational conditions. Atmospheric drag gradually lowers the station, so periodic reboost manoeuvres are required to restore its altitude.","The station's orbital eccentricity is approximately 0.0002267, making its orbit nearly circular. Its altitude, orbital position and visibility continuously change as the station travels around Earth."] },
  { id:"structure", title:"04 / STRUCTURE", heading:"A city-sized spacecraft made of modules.", text:["The ISS combines pressurised laboratories and living modules with an enormous external truss, solar arrays, radiators, robotic systems and docking ports. Major elements include Zarya, Unity, Zvezda, Destiny, Quest, Poisk, Harmony, Tranquility, Columbus, Kibō, Cupola, Rassvet, Leonardo, BEAM, International Docking Adapters, Bishop, Nauka and Prichal.","The Integrated Truss Structure carries power, thermal-control equipment and the station's solar arrays. Canadarm2 and other robotic systems move equipment and visiting spacecraft and support external maintenance."] },
  { id:"countries", title:"05 / COUNTRIES INVOLVED", heading:"International cooperation, assembled in orbit.", text:["The ISS is operated through a partnership involving NASA, Roscosmos, the European Space Agency (ESA), the Japan Aerospace Exploration Agency (JAXA), and the Canadian Space Agency (CSA).", "NASA leads the United States orbital segment; Roscosmos operates the Russian segment; ESA supplies and operates European hardware including Columbus; JAXA operates the Japanese Kibō laboratory; and Canada provides the Mobile Servicing System and Canadarm2 robotics.","The station's architecture reflects that partnership: different nations manufacture and operate different pieces, while the completed vehicle functions as one integrated spacecraft."] },
  { id:"orbit", title:"06 / ORBIT, DEBRIS & VISIBILITY", heading:"The ISS is always moving.", text:["The station travels prograde, west to east, at an average speed of about 28,000 kilometres per hour and completes about 15.5 orbits per day. Its 51.6-degree inclination allows the station to pass over a wide range of latitudes. Atmospheric drag reduces its altitude by about 2 km per month on average, so reboosts are performed to maintain the orbit.","The Russian Orbital Segment contains the Data Management System responsible for guidance, navigation and control for the station. Zvezda uses redundant sensors and fault-tolerant computers to determine the station's position and orbital trajectory. Gyroscopes help control orientation, while thrusters are used when momentum needs to be cancelled or orbital changes are required.","The ISS shares low Earth orbit with space debris, including spent rocket stages, defunct satellites and fragments. Smaller objects can be particularly dangerous because they may be difficult to detect while carrying significant kinetic energy. The station uses shielding on pressurised sections and critical systems, while debris is tracked from the ground. If a predicted conjunction presents a sufficient threat, operators can perform a Debris Avoidance Manoeuvre.","The ISS can also be seen from Earth as a bright, fast-moving white point when it crosses a suitable part of the sky while illuminated by the Sun. Visibility depends on location, orbital position, season, sunlight geometry and local conditions. It can be visible to the naked eye during suitable twilight passes, and telescope or binocular observations can reveal more detail."] },
  { id:"environment", title:"07 / ENVIRONMENT & CREW HEALTH", heading:"A hostile environment outside a controlled habitat.", text:["Gravity at the altitude of the ISS is still approximately 90% as strong as at Earth's surface, but the station and its contents are in continuous freefall, producing the weightlessness known as microgravity. Residual atmospheric drag, vibration, gyroscope operation, thruster firings and gravity-gradient effects disturb this state.","The ISS is partially protected from the space environment by Earth's magnetic field, but crews remain exposed to radiation from cosmic rays and solar activity. Radiation can damage living tissue and increase health risks, so shielding, monitoring and operational procedures are used to manage exposure.","Microbiological hazards are also monitored. Molds and bacteria can affect air, water, materials and crew health, so humidity control, material testing, cleaning and dedicated experiments are used to understand and manage microbial growth.","Noise is another long-duration environmental concern. Pumps, fans, ventilation systems, spacecraft and experiments contribute to the acoustic environment, so NASA and the international partners use engineering controls, acoustic materials, monitoring and hearing-protection procedures to reduce risk.","Fire and toxic-gas leaks are additional hazards. Ammonia, used in the station's external radiators, is one example of a substance that could pose a danger if it entered pressurised areas."] },
  { id:"life", title:"08 / LIFE ABOARD", heading:"Living without up or down.", text:["Crew quarters are compact and personal. Astronauts sleep in individual sleeping bags attached to walls, work in laboratories, exercise for roughly two hours a day, maintain equipment, conduct research and communicate with people on Earth.","Food is packaged for spaceflight and prepared with limited water and equipment. Personal hygiene relies on wipes, rinse-free methods and careful water management rather than conventional showers. Cupola windows provide a view of Earth and support Earth observation and photography."] },
  { id:"science", title:"09 / SCIENCE", heading:"What can we learn only by going up?", text:["Microgravity lets researchers isolate effects that gravity masks on Earth. Experiments investigate protein crystals, cell biology, plant growth, fluid behaviour, combustion, materials, medicine and the effects of long-duration spaceflight on humans.","The station is also a technology testbed. Systems for water recovery, life support, robotics, communications and spacecraft operations can be tested in the actual environment where future exploration systems will have to work."] },
  { id:"cost", title:"10 / COST", heading:"The most expensive single object ever constructed.", text:["The ISS has been described as the most expensive single item ever constructed. A 2010 estimate put the total cost at about US$150 billion. The cited breakdown included NASA's US$58.7 billion budget for the station from 1985 to 2015, Russia's US$12 billion, Europe's US$5 billion, Japan's US$5 billion and Canada's US$2 billion.","The 36 Space Shuttle flights used for construction were estimated at US$1.4 billion each, or US$50.4 billion in total. Using an estimate of 20,000 crew-days between 2000 and 2015, the historical calculation put the cost at about US$7.5 million per crew-day. The cited inflation-adjusted comparison for Skylab was about US$19.6 million per crew-day.","NASA was reported as spending about US$3 billion per year on operational costs. These are historical estimates tied to the periods and assumptions under which they were calculated."] },
  { id:"future", title:"11 / END OF MISSION", heading:"The station will not orbit forever.", text:["The ISS is a finite spacecraft operating in an environment that continuously degrades it. Its partners have extended operations while planning what comes next, including commercial space stations and future human exploration beyond low Earth orbit.","NASA and its partners have planned a controlled end-of-life disposal strategy. A dedicated U.S. Deorbit Vehicle is intended to guide the station through a controlled atmospheric re-entry after operations conclude, with surviving debris directed toward a remote ocean region."] },
  { id:"culture", title:"12 / IN CULTURE", heading:"More than a machine.", text:["The ISS has become a symbol of scientific cooperation and human presence beyond Earth. It appears in documentaries, films, literature, games, educational programmes and public outreach, while astronaut photography has made the station and its view of Earth familiar to millions of people.","Its enduring legacy includes demonstrating that nations with different languages, political systems and engineering traditions can operate one complex spacecraft together for decades."] },
];

export default function MoreAboutISS() {
  return <main className="iss-info-page">
    <header className="topbar info-topbar"><Link href="/" className="brand info-brand"><div className="brand-logo"><img src="/logo.svg" alt="ISS spacecraft" /></div><span className="brand-title">LIVE ISS TRACKER</span></Link><nav className="site-nav" aria-label="Main navigation"><Link href="/">HOME</Link><span className="nav-current">MORE ABOUT ISS</span></nav></header>
    <section className="iss-info-hero"><div className="iss-info-kicker">INTERNATIONAL SPACE STATION / KNOWLEDGE BASE</div><h1>THE <em>ISS</em>, EXPLAINED.</h1><p>A structured field guide to the laboratory, spacecraft, science, people and orbital environment behind the live tracker.</p></section>
    <figure className="iss-feature-image"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/ISS%20March%202009.jpg" alt="The International Space Station photographed from Space Shuttle Discovery" /><figcaption>THE INTERNATIONAL SPACE STATION / PHOTOGRAPHED DURING STS-119 · NASA / PUBLIC DOMAIN</figcaption></figure>
    <div className="iss-layout"><aside className="iss-index"><div className="index-title">INDEX</div>{sections.map(s=><a key={s.id} href={`#${s.id}`}>{s.title}</a>)}</aside><article className="iss-content">
      {sections.map((s,index)=><section className="iss-section" id={s.id} key={s.id}><div className="section-number">{s.title}</div><h2>{s.heading}</h2>{s.text.map(p=><p key={p}>{p}</p>)}{index===3&&<figure className="iss-diagram"><img src="https://commons.wikimedia.org/wiki/Special:FilePath/Iss-blowout-updated-view-2023-300.png" alt="Exploded diagram showing the elements of the International Space Station"/><figcaption>ISS CONFIGURATION / STATION ELEMENTS · NASA / PUBLIC DOMAIN</figcaption></figure>}</section>)}
      <section className="iss-sources"><div className="section-number">SOURCES</div><h2>International Space Station references.</h2><p>Information on this page is sourced from Wikipedia's International Space Station article and official NASA material. Images are from NASA's official public-domain media.</p><div className="source-links"><a href="https://en.wikipedia.org/wiki/International_Space_Station" target="_blank" rel="noreferrer">WIKIPEDIA / INTERNATIONAL SPACE STATION ↗</a><a href="https://www.nasa.gov/international-space-station/" target="_blank" rel="noreferrer">NASA / INTERNATIONAL SPACE STATION ↗</a></div></section>
    </article></div>
    <footer className="iss-info-footer"><Link href="/">© ISS TRACKER</Link><span>EMAIL | LINKEDIN</span></footer>
  </main>;
}
